### ISSUE TITLE
Support multiple Elasticsearch versions

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/py-es-bulk#3]
(See original issue at: https://github.com/distributed-system-analysis/pbench/issues/816)

Various distributions handle python versions in their own way, but python packages are available via pip for 3.x as:

 * [elasticsearch1](https://pypi.org/project/elasticsearch1/)
 * [elasticsearch2](https://pypi.org/project/elasticsearch2/)
 * [elasticsearch5](https://pypi.org/project/elasticsearch5/)
 * [elasticsearch](https://pypi.org/project/elasticsearch/)

In our internal to Red Hat environment, we are currently stuck on Elasticsearch V1, but will be migrating to V5 soon.

It would be great to support these various versions since they are so localized.

**Comment by portante** [comment]
For example, on a RHEL 7 box, where we don't have python 3 easily available to us, I had to enable the Red Hat SCL (Software Collections Library), and then install the `rh-python36` RPM:

```
# subscription-manager repos --enable=rhel-server-rhscl-7-rpms
# yum install -y rh-python36
```

And then, use pip install to add all the elasticsearch library versions:

```
$ scl enable rh-python36 bash
rh-python36$ pip install elasticsearch1
rh-python36$ pip install elasticsearch2
rh-python36$ pip install elasticsearch5
rh-python36$ pip install elasticsearch
```

With that, the code is now still importing `elasticsearch` as the python module, which means we are going to be using the V6 client.  If the target version of the Elasticsearch is a V5 instance, we ought to consider using that version for our client, `index-pbench`, instead.

**Comment by portante** [comment]
Looks like the work performed in #8 to support V1 and V7 does not work as intended, see https://github.com/distributed-system-analysis/pbench/issues/1924.

**Comment by dbutenhof** [comment]
`pyesbulk` 2.0.1 tries to dynamically import the elasticsearch Python module used by the caller to create the `es` Elasticsearch object passed in to the two APIs.

Where this breaks down is in unit testing when `pyesbulk` is passed a fake test object (as in the Pbench testing environment). Because the mock object does not have a normal Python module package path, `pyesbulk` is unable to determine the correct module to import, and falls back to `elasticsearch`. This works fine if that's what the caller actually uses; however if it's using `elasticsearch1` or `elasticsearch5` (etc.) then the `except` clauses won't trigger because different exception classes are being returned. (And it's possible that `elasticsearch` isn't even installed.)

- One solution would be to add a kwarg like `module=elasticsearch1` which `pyesbulk` would import instead of the fixed fallback module. The downside is that this would require an `indexer.py` change rather than being isolated to the unit test framework.
- Another alternative would be to put a property on the mock Elasticsearch object that's unlikely to be provided by any real elasticsearch Python package, for example `force_elasticsearch_module=elasticsearch1` which `pyesbulk` would check for to override the normal module path search.

**Comment by portante** [comment]
Documenting that the Mock needs to provide a module name for the exact version of the Elasticsearch client to see seems reasonable.

**Comment by dbutenhof** [comment]
Done in PR #13
